using System.Reflection;
using System.Text;
using RCommon.ApiReferenceGenerator;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: RCommon.ApiReferenceGenerator <path-to-Src-directory> <output-file-path>");
    return 1;
}

var srcRoot = Path.GetFullPath(args[0]);
var outputPath = Path.GetFullPath(args[1]);

if (!Directory.Exists(srcRoot))
{
    Console.Error.WriteLine($"warning: Src directory not found at '{srcRoot}' -- skipping API reference generation.");
    return 0;
}

var assemblies = FindPackageAssemblies(srcRoot);
if (assemblies.Count == 0)
{
    Console.Error.WriteLine(
        $"warning: no built RCommon.*.dll assemblies found under '{srcRoot}'. " +
        "Run `dotnet build Src/RCommon.sln -c Release` first. Skipping API reference generation " +
        "(leaving any previously-generated output file in place).");
    return 0;
}

// Built once and reused for every assembly, keyed by simple assembly name with exactly one path per
// name so MetadataLoadContext can never be asked to resolve the same name to two different paths
// (which throws). Priority order: (1) RCommon's own sibling packages, resolved to the actual local
// build rather than any stale copy that might be sitting in the NuGet cache from a previous local
// pack/restore; (2) the NuGet package cache, for transitive framework dependencies RCommon's own
// projects don't copy into their own bin output (e.g. Microsoft.Extensions.*); (3) the runtime's own
// shared framework directory, for System.*/mscorlib.
var libraryPaths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
foreach (var path in assemblies)
{
    libraryPaths.TryAdd(Path.GetFileNameWithoutExtension(path), path);
}
foreach (var (name, path) in FindNuGetLibraryPaths())
{
    libraryPaths.TryAdd(name, path);
}
var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
foreach (var path in Directory.GetFiles(runtimeDir, "*.dll"))
{
    libraryPaths.TryAdd(Path.GetFileNameWithoutExtension(path), path);
}

var sections = new List<string>();
foreach (var assemblyPath in assemblies.OrderBy(p => Path.GetFileNameWithoutExtension(p), StringComparer.OrdinalIgnoreCase))
{
    try
    {
        sections.Add(RenderAssembly(assemblyPath, libraryPaths));
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"warning: failed to reflect over '{assemblyPath}': {ex.Message}");
    }
}

var packageCount = sections.Count;
var output = $"""
    # RCommon — Full API Reference

    > This file contains the complete public API surface of every RCommon.* package: every public
    > type and member, with signatures and XML doc-comment summaries.
    > Generated by Tools/RCommon.ApiReferenceGenerator by reflecting over built assemblies plus their
    > .xml doc-comment sidecars -- not hand-authored, so it will not go stale relative to the code.
    > For prose documentation, see https://rcommon.com/llms-full.txt

    ---

    {string.Join("\n\n---\n\n", sections)}

    """;

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, output);
Console.WriteLine($"Generated {Path.GetFileName(outputPath)}: {packageCount} package(s), {output.Length / 1024.0:F1} KB");
return 0;

static List<string> FindPackageAssemblies(string srcRoot)
{
    var preferredTfms = new[] { "net10.0", "net9.0", "net8.0" };
    var result = new List<string>();

    foreach (var projectDir in Directory.GetDirectories(srcRoot, "RCommon.*"))
    {
        var projectName = Path.GetFileName(projectDir);

        // Skip test/tooling-adjacent projects that happen to match the RCommon.* glob but aren't
        // shipped packages (none currently live directly under Src/, but this guards against it).
        if (projectName.EndsWith(".Tests", StringComparison.OrdinalIgnoreCase))
        {
            continue;
        }

        var csprojPath = Directory.GetFiles(projectDir, "*.csproj").FirstOrDefault();
        if (csprojPath == null)
        {
            continue;
        }

        // The output assembly name doesn't always match the project folder name (e.g. RCommon.EfCore's
        // assembly is RCommon.EFCore.dll) -- read <AssemblyName> if present, matching what MSBuild
        // itself uses, rather than guessing from a directory listing (which also contains copied
        // dependency DLLs that would otherwise be picked up by mistake).
        var assemblyName = ReadAssemblyNameOverride(csprojPath) ?? Path.GetFileNameWithoutExtension(csprojPath);

        string? found = null;
        foreach (var tfm in preferredTfms)
        {
            var candidate = Path.Combine(projectDir, "bin", "Release", tfm, assemblyName + ".dll");
            if (File.Exists(candidate) && File.Exists(Path.ChangeExtension(candidate, ".xml")))
            {
                found = candidate;
                break;
            }
        }

        if (found != null)
        {
            result.Add(found);
        }
    }

    return result;
}

static string? ReadAssemblyNameOverride(string csprojPath)
{
    var doc = System.Xml.Linq.XDocument.Load(csprojPath);
    return doc.Descendants("AssemblyName").FirstOrDefault()?.Value;
}

static Dictionary<string, string> FindNuGetLibraryPaths()
{
    // Highest-preference TFM first: for each simple assembly name, keep the path found under the
    // most preferred compatible TFM folder encountered first.
    var preferredTfmOrder = new[] { "net10.0", "net9.0", "net8.0", "netstandard2.1", "netstandard2.0" };
    var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    var nugetRoot = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".nuget", "packages");
    if (!Directory.Exists(nugetRoot))
    {
        return result;
    }

    foreach (var tfm in preferredTfmOrder)
    {
        foreach (var dll in Directory.EnumerateFiles(nugetRoot, "*.dll", SearchOption.AllDirectories)
                     .Where(p => p.Contains(Path.Combine("lib", tfm), StringComparison.OrdinalIgnoreCase)))
        {
            var name = Path.GetFileNameWithoutExtension(dll);
            result.TryAdd(name, dll);
        }
    }

    return result;
}

static string RenderAssembly(string assemblyPath, Dictionary<string, string> libraryPaths)
{
    var xmlPath = Path.ChangeExtension(assemblyPath, ".xml");
    var docs = File.Exists(xmlPath) ? XmlDocFile.Load(xmlPath) : new Dictionary<string, XmlDocMember>();

    // libraryPaths already has exactly one path per simple assembly name (RCommon siblings resolved to
    // their local build, everything else from the NuGet cache or the runtime directory) -- see where
    // it's built in Main for the priority order and why a single dictionary avoids MetadataLoadContext
    // being asked to resolve one name to two different paths.
    var resolver = new PathAssemblyResolver(libraryPaths.Values.Distinct());
    using var mlc = new MetadataLoadContext(resolver, coreAssemblyName: typeof(object).Assembly.GetName().Name);

    var assembly = mlc.LoadFromAssemblyPath(assemblyPath);
    var packageName = assembly.GetName().Name;

    var sb = new StringBuilder();
    sb.Append("## ").Append(packageName).Append('\n');

    var publicTypes = assembly.GetExportedTypes()
        // Skip the Roslyn-generated <Clone>$/record equality plumbing and compiler-generated types;
        // GetExportedTypes only returns real public types, so this is mostly a defensive filter.
        .Where(t => !t.IsSpecialName)
        .OrderBy(t => t.Namespace, StringComparer.Ordinal)
        .ThenBy(t => t.Name, StringComparer.Ordinal);

    foreach (var group in publicTypes.GroupBy(t => t.Namespace ?? "(no namespace)"))
    {
        sb.Append("\n### Namespace ").Append(group.Key).Append('\n');

        foreach (var type in group)
        {
            RenderType(sb, type, docs);
        }
    }

    return sb.ToString();
}

static void RenderType(StringBuilder sb, Type type, Dictionary<string, XmlDocMember> docs)
{
    var kind = type.IsInterface ? "interface" : type.IsEnum ? "enum" : type.IsValueType ? "struct" : "class";
    sb.Append("\n#### ").Append(kind).Append(' ').Append(FriendlyName(type)).Append('\n');

    if (docs.TryGetValue(MemberIdBuilder.ForType(type), out var typeDoc) && typeDoc.Summary != null)
    {
        sb.Append(typeDoc.Summary).Append('\n');
    }

    var members = GetPublicMembers(type);
    foreach (var member in members)
    {
        RenderMember(sb, member, docs);
    }
}

static IEnumerable<MemberInfo> GetPublicMembers(Type type)
{
    const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

    IEnumerable<MemberInfo> members = type.GetConstructors(flags)
        .Cast<MemberInfo>()
        .Concat(type.GetMethods(flags).Where(m => !m.IsSpecialName))
        .Concat(type.GetProperties(flags))
        .Concat(type.GetFields(flags))
        .Concat(type.GetEvents(flags));

    return members.OrderBy(m => m.Name, StringComparer.Ordinal);
}

static void RenderMember(StringBuilder sb, MemberInfo member, Dictionary<string, XmlDocMember> docs)
{
    var signature = member switch
    {
        ConstructorInfo c => FriendlyName(c.DeclaringType!) + "(" + string.Join(", ", c.GetParameters().Select(FriendlyParameter)) + ")",
        MethodInfo m => m.Name + "(" + string.Join(", ", m.GetParameters().Select(FriendlyParameter)) + ") : " + FriendlyName(m.ReturnType),
        PropertyInfo p => p.Name + " : " + FriendlyName(p.PropertyType),
        FieldInfo f => f.Name + " : " + FriendlyName(f.FieldType),
        EventInfo e => e.Name + " : " + FriendlyName(e.EventHandlerType!),
        _ => member.Name,
    };

    sb.Append("\n##### `").Append(signature).Append("`\n");

    string memberId;
    try
    {
        memberId = MemberIdBuilder.ForMember(member);
    }
    catch
    {
        memberId = string.Empty;
    }

    if (memberId.Length > 0 && docs.TryGetValue(memberId, out var doc))
    {
        if (doc.Summary != null)
        {
            sb.Append(doc.Summary).Append('\n');
        }
        foreach (var (name, text) in doc.Params)
        {
            sb.Append("- `").Append(name).Append("`: ").Append(text).Append('\n');
        }
        if (doc.Returns != null)
        {
            sb.Append("- Returns: ").Append(doc.Returns).Append('\n');
        }
        foreach (var exceptionType in doc.Exceptions)
        {
            sb.Append("- Throws: `").Append(exceptionType).Append("`\n");
        }
    }
}

static string FriendlyParameter(ParameterInfo parameter) => FriendlyName(parameter.ParameterType) + " " + parameter.Name;

static string FriendlyName(Type type)
{
    if (type.IsGenericType)
    {
        var name = type.Name[..type.Name.IndexOf('`')];
        var args = string.Join(", ", type.GetGenericArguments().Select(FriendlyName));
        return name + "<" + args + ">";
    }
    return type.Name;
}
