// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Samples.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Data;


using System.Linq;


using System.Threading;


using System.Threading.Tasks;


namespace Samples.ObjectAccess.EFCore
{

    public interface ISamplesContext

    {



        DbSet<DiveLocation> DiveLocations { get; set; } // DiveLocations


        DbSet<DiveLocationDetail> DiveLocationDetails { get; set; } // DiveLocationDetails


        DbSet<DiveType> DiveTypes { get; set; } // DiveTypes



    }
}
// </auto-generated>

