using RCommon.Entities;

namespace Examples.Persistence.Dapper;

// Dommel treats the "Id" key as database-generated by convention, excluding it from the INSERT
// statement and retrieving it afterward via provider-specific SQL (registered through
// DommelMapper.AddSqlBuilder in Program.cs). An int key maps naturally onto SQLite's own
// INTEGER PRIMARY KEY rowid-alias auto-increment behavior.
public class Product : BusinessEntity<int>
{
    public string Name { get; set; } = string.Empty;
    public string Sku { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int StockQuantity { get; set; }
}
