// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RCommon.DataServices;
using RCommon.TestBase.Entities;
using System;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace RCommon.Persistence.EFCore.Tests
{
    public interface ITestDbContext
    {
        DbSet<Customer> Customers { get; set; } // Customers
        DbSet<Department> Departments { get; set; } // Departments
        DbSet<MonthlySalesSummary> MonthlySalesSummaries { get; set; } // MonthlySalesSummary
        DbSet<Order> Orders { get; set; } // Orders
        DbSet<OrderItem> OrderItems { get; set; } // OrderItems
        DbSet<Product> Products { get; set; } // Products
        DbSet<SalesPerson> SalesPersons { get; set; } // SalesPerson
        DbSet<SalesTerritory> SalesTerritories { get; set; } // SalesTerritory
    }
}
// </auto-generated>

