// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RCommon.Samples.ConsoleApp.Domain.Entities
{
    // Customers
    public partial class Customer
    {
        public int CustomerId { get; set; } // CustomerID (Primary key)
        public string StreetAddress1 { get; set; } // StreetAddress1 (length: 255)
        public string StreetAddress2 { get; set; } // StreetAddress2 (length: 255)
        public string City { get; set; } // City (length: 255)
        public string State { get; set; } // State (length: 255)
        public string ZipCode { get; set; } // ZipCode (length: 255)
        public string FirstName { get; set; } // FirstName (length: 255)
        public string LastName { get; set; } // LastName (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child Orders where [Orders].[CustomerId] point to this entity (FK_Customer_Orders)
        /// </summary>
        public virtual ICollection<Order> Orders { get; set; } // Orders.FK_Customer_Orders

        public Customer()
        {
            Orders = new List<Order>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

