// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RCommon.TestBase.Entities
{
    // Products
    public partial class Product
    {
        public int ProductId { get; set; } // ProductID (Primary key)
        public string Name { get; set; } // Name (length: 255)
        public string Description { get; set; } // Description (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child OrderItems where [OrderItems].[ProductId] point to this entity (FK_OrderItems_Product)
        /// </summary>
        public virtual ICollection<OrderItem> OrderItems { get; set; } // OrderItems.FK_OrderItems_Product

        public Product()
        {
            OrderItems = new List<OrderItem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

