// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using RCommon.TestBase.Entities;

namespace RCommon.ObjectAccess.EFCore.Tests
{
    // MonthlySalesSummary
    public partial class MonthlySalesSummaryConfiguration : IEntityTypeConfiguration<MonthlySalesSummary>
    {
        public void Configure(EntityTypeBuilder<MonthlySalesSummary> builder)
        {
            builder.ToTable("MonthlySalesSummary", "dbo");
            builder.HasKey(x => new { x.Year, x.Month, x.SalesPersonId }).HasName("PK__MonthlyS__C26E735F2ADBDAB9").IsClustered();

            builder.Property(x => x.Year).HasColumnName(@"Year").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Month).HasColumnName(@"Month").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SalesPersonId).HasColumnName(@"SalesPersonId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("decimal(19,5)").IsRequired(false);
            builder.Property(x => x.Currency).HasColumnName(@"Currency").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);
            builder.Property(x => x.SalesPersonFirstName).HasColumnName(@"SalesPersonFirstName").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);
            builder.Property(x => x.SalesPersonLastName).HasColumnName(@"SalesPersonLastName").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);

        }
    }

}
// </auto-generated>

