// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using RCommon.BusinessEntities;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RCommon.ObjectAccess.EFCore.Tests
{
    // Orders
    public partial class Order : IBusinessEntity
    {
        public int OrderId { get; set; } // OrderID (Primary key)
        public DateTime? OrderDate { get; set; } // OrderDate
        public DateTime? ShipDate { get; set; } // ShipDate
        public int? CustomerId { get; set; } // CustomerId

        // Reverse navigation

        /// <summary>
        /// Child OrderItems where [OrderItems].[OrderId] point to this entity (FK_Orders_OrderItems)
        /// </summary>
        public virtual ICollection<OrderItem> OrderItems { get; set; } // OrderItems.FK_Orders_OrderItems

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [Orders].([CustomerId]) (FK_Customer_Orders)
        /// </summary>
        public virtual Customer Customer { get; set; } // FK_Customer_Orders

        public Order()
        {
            OrderItems = new List<OrderItem>();
            InitializePartial();
        }

        partial void InitializePartial();

        public object[] GetKeys()
        {
            throw new NotImplementedException();
        }
    }

}
// </auto-generated>

