// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RCommon.ObjectAccess.EFCore.Tests
{
    // SalesTerritory
    public partial class SalesTerritory
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 255)
        public string Description { get; set; } // Description (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child SalesPersons where [SalesPerson].[TerritoryId] point to this entity (FK74214A90B23DB0A3)
        /// </summary>
        public virtual ICollection<SalesPerson> SalesPersons { get; set; } // SalesPerson.FK74214A90B23DB0A3

        public SalesTerritory()
        {
            SalesPersons = new List<SalesPerson>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

